// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDENHn71luKZHXkyME5EBHMQDlu0eu1D3w',
    appId: '1:828591222677:web:0debea229f616ca122109c',
    messagingSenderId: '828591222677',
    projectId: 'sample-notification-app-a512d',
    authDomain: 'sample-notification-app-a512d.firebaseapp.com',
    storageBucket: 'sample-notification-app-a512d.appspot.com',
    measurementId: 'G-TF05FZ4QW2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4iBVj6Ayx8SVSb3fnLwt3Rzv40uqe3mQ',
    appId: '1:828591222677:android:557c47af44cb8ddf22109c',
    messagingSenderId: '828591222677',
    projectId: 'sample-notification-app-a512d',
    storageBucket: 'sample-notification-app-a512d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrvcsvNjhAZmqwfldUxiNGtNGaF7_hdQY',
    appId: '1:828591222677:ios:efdad91cab9d76fc22109c',
    messagingSenderId: '828591222677',
    projectId: 'sample-notification-app-a512d',
    storageBucket: 'sample-notification-app-a512d.appspot.com',
    iosClientId: '828591222677-jfnmvrava7lailget7pqe53h8bvo4iqj.apps.googleusercontent.com',
    iosBundleId: 'com.example.notificationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrvcsvNjhAZmqwfldUxiNGtNGaF7_hdQY',
    appId: '1:828591222677:ios:efdad91cab9d76fc22109c',
    messagingSenderId: '828591222677',
    projectId: 'sample-notification-app-a512d',
    storageBucket: 'sample-notification-app-a512d.appspot.com',
    iosClientId: '828591222677-jfnmvrava7lailget7pqe53h8bvo4iqj.apps.googleusercontent.com',
    iosBundleId: 'com.example.notificationApp',
  );
}
